### ISSUE TITLE
Reporting ceases if an exception is thrown

### ISSUE THREAD

**Issue by Dale-M** [CxxTest/cxxtest#115]
cxxtest-4.3 on gcc-(4.9.1|4.4.6), python-2.6.6.

From RealDescriptions.cpp:124 the message "Exception thrown from test" is not being passed down to TestTracker::failedTest (getting a nullptr instead), and then at ErrorFormatter.h:151 the null pointer is being sent into an output stream blocking all further output on that stream.

I have fixed the problem in my installation by checking for nullptr in ErrorFormatter:151:failedTest and outputting an empty string in that case.  I made the change to the other failed*() functions to be safe.  Probably the real problem is elsewhere....

**Comment by Dale-M** [comment]
I've seen the problem is in the test code passing back an exception with nullptr as the return from what().  I do think that the changes I made to ErrorFormatter described above should go in to cover this case, though.

**Comment by atomgalaxy** [comment]
If anyone writes their own test macros this is still an issue, as the do* functions are effectively public interface for their implementation and should be able to handle nulls in messages.
