### ISSUE TITLE
C string DIFFERS not consistent with EQUALS

### ISSUE THREAD

**Issue by Beuc** [CxxTest/cxxtest#122]
Hi,

The following test passes:

```
char str[] = "toto";
TS_ASSERT_EQUALS(str, "toto");
TS_ASSERT_DIFFERS(str, "toto");
```

That is, str is both equal and not equal to "toto".

I suspect a new EQUALS comparator was added for C strings, but DIFFERS must still rely on basic pointer comparison.

This was really unsettling when I reversed a test to check failure output, and saw it pass anyway %)

**Comment by Oliviers-OSS** [comment]
Hi,

Yes, you're right, a few time ago I've modified the equals test (cf. #81 then #83 & #84) but I've missed to do the same kind of modifications into the differs, oops !

Thank you're analyze, the file to modified is cxxtest/TestSuite.h, 3 specialized templates "template<class X, class Y> struct differs  " must be added for const char* and char* .

Best regards,

Olivier

**Comment by atomgalaxy** [comment]
This has been merged and a test added (CharAssertions.h)
